language: ruby

sudo: false

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4

before_install:
  - wget http://www.us.apache.org/dist/kafka/0.11.0.1/kafka_2.12-0.11.0.1.tgz -O kafka.tgz
  - mkdir -p kafka && tar xzf kafka.tgz -C kafka --strip-components 1
  - nohup bash -c "cd kafka && bin/zookeeper-server-start.sh config/zookeeper.properties &"
  - nohup bash -c "cd kafka && bin/kafka-server-start.sh config/server.properties &"

before_script:
  - cd ext && bundle exec rake && cd ..
  - bundle exec rake create_topics

script:
  - bundle exec rspec
